---

- name: Create VMs
  hosts: localhost
  vars_prompt:
    - name: key_name
      prompt: Key name?
      private: false
    - name: network
      prompt: Network?
      private: false
  roles:
    - instances
    - openstack_facts
    - demo

- name: Configure VMs
  hosts: created_instances
  gather_facts: false
  become: true
  roles:
    - dask
